---
- name: install 389-DS LDAP server
  tags:
    - 389ds
    - package-install
    - network
  package: name=389-ds-base state=present

- name: create 389-DS instance
  tags:
    - 389ds
  command: setup-ds \
    --silent \
    General.FullMachineName='{{ ansible_fqdn }}' \
    General.SuiteSpotUserID=nobody \
    General.SuiteSpotGroup=nogroup \
    slapd.ServerPort={{ldap_port}} \
    slapd.ServerIdentifier='{{pki_instance_name}}' \
    slapd.Suffix='{{suffix}}' \
    slapd.RootDN='cn=Directory Manager' \
    slapd.RootDNPwd='{{ dm_password }}'
  args:
    creates: /etc/dirsrv/slapd-{{pki_instance_name}}
