---
# - name: safe-guard against race condition
#  hosts: all
#  pre_tasks:
    # https://github.com/mitchellh/vagrant/issues/6526
#    - name: "wait for the node to be ready"
#      tags:
#        - bootstrap
#      become: false
#      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} delay=1

- name: install Dogtag PKI CA
  hosts: pkiserver
  roles:
    - pki-ca
    - pki-kra
