---
- include: pkiinstall.yml

- name: write PKI CA config template
  tags:
    - pkica
    - pkicaconfig
  template: src=templates/pki.cfg.j2 dest=/tmp/{{pki_instance_name}}-pkica.cfg

- name: create CA
  tags:
    - pkica
  command: pkispawn -f /tmp/{{pki_instance_name}}-pkica.cfg -s CA
  args:
    creates: /etc/pki/{{pki_instance_name}}/ca/CS.cfg

# - include: limitmemory.yml
# - include: fetchadmincert.yml
