---
- name: install pki-server packages and dependencies
  tags:
    - pki
    - package-install
  package: name={{ item }} state=present
  with_items:
    - pki-ca
    - pki-server
    - dogtag-pki-server-theme
    - openssl
  # when: package_install

